name: PyTorch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.7
  - numpy==1.15.4
  - scipy==1.1.0
  - scikit-learn==0.20.1
  - matplotlib
  - jupyter==1.0
  - notebook==5.7.4
  - pandas==0.23.4
  - ipython
  - pytorch
  - torchvision
  - pip
